# Generated by Django 5.1 on 2024-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty_log",
            name="faculty_log",
            field=models.FileField(null=True, upload_to="logfiles/faculty_logs/"),
        ),
        migrations.AlterField(
            model_name="faculty_log",
            name="faculty_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="student_log",
            name="student_log",
            field=models.FileField(null=True, upload_to="logfiles/students_logs/"),
        ),
        migrations.AlterField(
            model_name="student_log",
            name="student_name",
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name="OtpToken",
        ),
    ]
